# Generated by Django 3.0.4 on 2020-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Po',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pos/pdfs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
