# Generated by Django 3.0.4 on 2020-03-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200318_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='po',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
