# Generated by Django 3.0.4 on 2020-03-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200322_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po',
            name='date',
        ),
    ]
