# Generated by Django 3.0.4 on 2020-04-25 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_po_choose'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='choose',
            field=models.CharField(choices=[('BestSeller', 'BestSeller'), ('TomTailor', 'TomTailor'), ('TomyHill', 'TomyHill')], default=datetime.datetime(2020, 4, 25, 15, 39, 33, 464001, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
