# Generated by Django 3.0.4 on 2020-04-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200428_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Po_size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XXS', models.CharField(blank=True, max_length=100, null=True)),
                ('XS', models.CharField(blank=True, max_length=100, null=True)),
                ('S', models.CharField(blank=True, max_length=100, null=True)),
                ('M', models.CharField(blank=True, max_length=100, null=True)),
                ('L', models.CharField(blank=True, max_length=100, null=True)),
                ('XL', models.CharField(blank=True, max_length=100, null=True)),
                ('XXL', models.CharField(blank=True, max_length=100, null=True)),
                ('XXXL', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='po',
            name='L',
        ),
        migrations.RemoveField(
            model_name='po',
            name='M',
        ),
        migrations.RemoveField(
            model_name='po',
            name='S',
        ),
        migrations.RemoveField(
            model_name='po',
            name='XL',
        ),
        migrations.RemoveField(
            model_name='po',
            name='XS',
        ),
        migrations.RemoveField(
            model_name='po',
            name='XXL',
        ),
        migrations.RemoveField(
            model_name='po',
            name='XXS',
        ),
        migrations.RemoveField(
            model_name='po',
            name='XXXL',
        ),
        migrations.RemoveField(
            model_name='po',
            name='total',
        ),
    ]
